# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for tod
  pod 'JSONModel'
  pod 'SDWebImage', '~> 4.0'

  target 'todTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
